# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'mlive' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for mlive
  pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'
  target 'mlive-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'RNDeviceInfo', :path => '../node_modules/react-native-device-info'

    pod 'react-native-video', :path => '../node_modules/react-native-video'

    pod 'react-native-blur', :path => '../node_modules/react-native-blur'

  end

  target 'mliveTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

