# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'mlive' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for mlive
  pod 'AppCenterReactNativeShared', '~> 1.1.0'

  

  target 'mliveTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'mlive-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for mlive-tvOS

  target 'mlive-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
